[dev]
  functions = "src"
  functionsPort = 7000
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200